name: Deploying Docker Image
run-name: Automatic Building of Docker
on: [push]
jobs:
  builds-docker:
    runs-on: ubuntu-latest
    env:
        VERSION: 1.0
        USER: West-Computing-Club
    steps:
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Checkout Code
        uses: actions/checkout@v4

    -
        name: Login to ghcr.io
        run: docker login ghcr.io -u {{vars.USER}} --password-stdin {{secrets.PASSWORD}}
    -
        name: Build Docker Image
        run: docker build . -t  "${github.repository_owner}:${env.VERSION}"
    -
        name: Publish Docker Image to ghrc.io
        run: docker push ghcr.io/${github.repository_owner}:latest

