name: Deploying Docker Image
run-name: Automatic Building of Docker
on: [
    push:
        branches:
            - main
            - deploy
jobs:
  builds-docker:
    runs-on: ubuntu-latest
    permissions:
        packages: write
    env:
        VERSION: 1.0
        USER: west-computing-club
        IMAGE: distributed-code-edu
    steps:
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Checkout Code
        uses: actions/checkout@v4

    - 
        name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u "${{ vars.USER }}" --password-stdin
    -
        name: Build Docker Image
        run: docker build . -t  ghcr.io/${{ env.USER}}/${{env.IMAGE}}:${{env.VERSION}}
    -
        name: Publish Docker Image to ghrc.io
        run: docker push ghcr.io/${{ env.USER}}/${{env.IMAGE}}:${{env.VERSION}}

