name: Deploying Docker Image
run-name: Automatic Building of Docker
on: [push]
jobs:
  builds-docker:
    runs-on: ubuntu-latest
    env:
        VERSION: 1.0
        USER: West-Computing-Club
        IMAGE: wc3-distributed-club-edu
    steps:
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Checkout Code
        uses: actions/checkout@v4

    - 
        name: Login to ghcr.io
        run: echo "${{ secrets.PASSWORD }}" | docker login ghcr.io -u "${{ vars.USER }}" --password-stdin
    -
        name: Build Docker Image
        run: docker build . -t  "${{env.IMAGE}}"
    -
        name: Publish Docker Image to ghrc.io
        run: docker push ghcr.io/${{ env.USER}}/${{env.IMAGE}}:latest

